### ISSUE TITLE
pkg_resources.DistributionNotFound: nltk-contrib==3.1

### ISSUE THREAD

**Issue by adeshgupta** [manalishah/NLTKRest#12]
`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (nltk-contrib 3.2 (/usr/local/lib/python3.4/dist-packages), Requirement.parse('nltk-contrib==3.1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/nltk-server", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: nltk-contrib==3.1
`
It gives me the above error when I am trying to start the nltk-server. Please help. I am using Ubuntu

**Comment by chrismattmann** [comment]
Hi @adeshgupta , FYI, you need to run per the [README](https://github.com/manalishah/NLTKRest/blob/master/nltkrest/README.md):

```
pip2.7 install --process-dependency-links nltkrest 
```

If you aren't using python2.7 or pip2.7 remove the 2.7 above.

**Comment by mit2nil** [comment]
It would be great if "http://wiki.apache.org/tika/TikaAndNLTK" is updated with correct command as step1 given there is not working.

**Comment by manalishah** [comment]
@mit2nil it has been updated!
